### PR TITLE
Allow only distinct blog posts

### PR DESCRIPTION
**Pull request by lparsons396**
[Link to Ticket](https://torchbox.monday.com/boards/1192293412/pulses/1409752818)

### Description of Changes Made
- Implement fix to prevent duplicated blog posts being shown on a BlogIndexPage
- I've also confirmed that this is not necessary on WorkIndexPages

### How to Test
Confirm that no duplicate blog posts are present when filtering is applied - you could also include a print statement or logging to confirm no duplicates are present 

### Screenshots
Without Fix
image

With Fix
image

<details>
  <summary>Expand to see more</summary>

</details>

### MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [x] Tests and linting passes.

#### Unit tests

- [ ] Added
- [x] Not required

#### Documentation

- [ ] Updated build docs
- [ ] Updated editor guidelines (https://docs.google.com/document/d/1PAWccdQ4tfaZsrEWmpDhvP3GH5RRmBOARFVp4b-kje8/edit?usp=sharing)
- [x] Not required

#### Browser testing

- [ ] I have tested in the following browsers and environments (edit the list as required)
  - Latest version of Chrome on mac
  - Latest version of Firefox on mac
  - Latest version of Safari on mac
  - Safari on last two versions of iOS
  - Chrome on last two versions of Android
- [x] Not required

#### Data protection

- [ ] Not relevant
- [ ] This adds new sources of PII and documents it and modifies Birdbath processors accordingly

#### Accessibility

- [ ] Automated WCAG 2.1 tests pass
- [ ] Manual WCAG 2.1 tests completed
- [ ] I have tested in a screen reader
- [ ] I have tested in high-contrast mode
- [ ] Any animations removed for prefers-reduced-motion
- [x] Not required

#### Sustainability

- [ ] Images are optimised and lazy-loading used where appropriate
- [ ] SVGs have been optimised
- [ ] Perfomance and transfer of data considered
- [ ] If JavaScript is needed alternatives have been considered
- [x] Not required

#### Pattern library

- [ ] The pattern library component for this template displays correctly, and does not break parent templates
- [ ] The styleguide is updated if relevant
- [x] Changes are not relevant the pattern library

### CODE REVIEW

**Review by engineervix — APPROVED** [review]
Nice one @lparsons396 :+1: 

looks like there'll be a bit of work to bring the branch up to date before merging!

**Comment by lparsons396** [comment]
Done in https://github.com/torchbox/torchbox.com/commit/a9a18cce8c75a4423492adc4740ddc0e381b6b89

**Comment by helenb** [comment]
@lparsons396 did you mean to close this PR without merging it?

**Comment by lparsons396** [comment]
> @lparsons396 did you mean to close this PR without merging it?

Yes, I included straight on the integration branch see https://github.com/torchbox/torchbox.com/pull/136#issuecomment-1980503733

**Pull request closed without merging**
