### PR TITLE
BE & FE | Featured Case Study Block: Numeric stats

### PR DESCRIPTION
**Pull request by SharmaineLim**
[Link to Ticket](https://torchbox.monday.com/boards/1192293412/pulses/1426626508)

### Description of Changes Made

- Add new `numeric_results` field to `FeaturedCaseStudyBlock`. Each numeric result will have a label and number.
- The `text` field is kept as a text-based alternative to the numeric results field. (Between `numeric_results` and `text`, only one can be populated.)
- Both will be treated as "Results", and the results icon will display (on desktop only) if either field is populated.

Related changes:

- Make the featured case study block start from the left-most edge on mobile, to match the design.

### How to Test

- View the featured case study block on the pattern library. ([local](http://localhost:8000/pattern-library/pattern/patterns/molecules/streamfield/blocks/featured_case_study.html))
- View the home page on the pattern library. ([local](http://localhost:8000/pattern-library/pattern/patterns/pages/home/home_page.html))
- View the service page on the pattern library. ([local](http://localhost:8000/pattern-library/pattern/patterns/pages/service/service_page.html))
- On the home page, add a featured case study block with numeric results, then check the preview. ([local](http://localhost:8000/admin/pages/5/edit/))
- On a service page, add a featured case study block with numeric results, then check the preview. ([local](http://localhost:8000/admin/pages/2192/edit/))

### Screenshots

<details><summary>Mobile</summary>

image

</details>

<details><summary>Desktop</summary>

image

</details>

### MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [x] Tests and linting passes.

#### Unit tests

- [x] Not required

#### Documentation

- [x] Updated editor guidelines (https://docs.google.com/document/d/1PAWccdQ4tfaZsrEWmpDhvP3GH5RRmBOARFVp4b-kje8/edit#heading=h.l0r3tyi9vug8)

#### Browser testing

- [x] I have tested in the following browsers and environments (edit the list as required)
  - Latest version of Chrome on mac
  - Latest version of Firefox on mac
  - Latest version of Safari on mac
  - Safari on last two versions of iOS (1 real, 1 on Browserstack)
  - Chrome on last two versions of Android (2 on Browserstack)

#### Data protection

- [x] Not relevant

#### Accessibility

- [x] Automated WCAG 2.1 tests pass
- [x] HTML validation passes
- [x] Manual WCAG 2.1 tests completed
- [x] I have tested in a screen reader
- [x] I have tested in high-contrast mode
- [x] Any animations removed for prefers-reduced-motion

#### Sustainability

- [x] Images are optimised and lazy-loading used where appropriate
- [x] SVGs have been optimised
- [x] Perfomance and transfer of data considered
- [x] ~~If JavaScript is needed alternatives have been considered~~

#### Pattern library

- [x] The pattern library component for this template displays correctly, and does not break parent templates
- [x] The styleguide is updated if relevant

### CODE REVIEW

**Comment by helenb** [comment]
I'm editing an existing page with a featured case study, which already had some textual results. It seems like the results stats are required, which isn't expected from the description for this PR. In addition the results stats are displaying the word 'None'


Screenshot 2024-03-26 at 15 00 07

Screenshot 2024-03-26 at 15 00 00

**Comment by helenb** [comment]
> I'm editing an existing page with a featured case study, which already had some textual results. It seems like the results stats are required, which isn't expected from the description for this PR. In addition the results stats are displaying the word 'None'
> 
> Screenshot 2024-03-26 at 15 00 07
> 
> Screenshot 2024-03-26 at 15 00 00

I found that I'm able to save the page if I delete the initial 'Numeric results' item that appears automatically, but not if I don't. I think we need to remove that initial field and leave the editor to select to add it.

**Review by engineervix — APPROVED** [review]
Thanks Amanda, BE changes LGTM :+1:

**Comment by SharmaineLim** [comment]
> just needs the wagtail edit interface updating so we don't end up with an empty numeric stats block and the 'none' text appearing.

This should be addressed by [b968e8b](https://github.com/torchbox/torchbox.com/pull/191/commits/b968e8b3cbfb6a0607a8926aa6232182bb3629d2).

**Pull request merged**
