### PR TITLE
Wagtail 6 Upgrade

### PR DESCRIPTION
**Pull request by engineervix**
[Link to Ticket](https://torchbox.monday.com/boards/1192293412/pulses/1435768302)

### Description of Changes Made

This upgrades Wagtail to version 6, based on the [upgrade considerations](https://docs.wagtail.org/en/latest/releases/6.0.html#upgrade-considerations-removal-of-deprecated-features-from-wagtail-4-2-5-1) documented in the release notes.

Having gone through the upgrade considerations, the following changes have been made:

1. Removal of `use_json_field=True` from `StreamField`, as it's [no longer required](https://docs.wagtail.org/en/latest/releases/6.0.html#streamfield-no-longer-requires-use-json-field-true) (fac236f)
2. Removal of `widget=SlugInput` on `SlugField` fields, since [this is now the default](https://docs.wagtail.org/en/latest/releases/6.0.html#sluginput-widget-is-now-the-default-for-slugfield-fields) (2b12a87)

Bumping wagtail from 5.2 to 6.0 necessitated the following additional package upgrades:

- [wagtail-purge](https://github.com/torchbox/wagtail-purge), from v0.3.0 to v0.4.0 (c9b20f9)
- [wagtailmedia](https://github.com/torchbox/wagtailmedia), from v0.14.5 to v0.15.1 (becb04b)

Additionally, I have

- bumped Django from 4.2.9 to [4.2.11](https://docs.djangoproject.com/en/5.0/releases/4.2.11/), so we have the latest security updates in the current LTS release. (4ce7756)
- rearranged the dependencies in `pyproject.toml` so as to make it easier to spot packages that are likely to be affected by a wagtail upgrade (c9b20f9)

### How to Test

Please see the ACs on the ticket.

### Screenshots

<details>
  <summary>Wagtail admin</summary>

image

image

image

image

</details>

<details>
  <summary>Sluginput</summary>

https://github.com/torchbox/torchbox.com/assets/7713776/191225b4-e75d-470d-af4f-815ed36ea3df

</details>

### MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [x] Tests and linting passes.

#### Unit tests

- [ ] Added
- [x] Not required

#### Documentation

- [ ] Updated build docs
- [ ] Updated editor guidelines (https://docs.google.com/document/d/1PAWccdQ4tfaZsrEWmpDhvP3GH5RRmBOARFVp4b-kje8/edit?usp=sharing)
- [x] Not required

#### Browser testing

- [x] I have tested in the following browsers and environments (edit the list as required)
  - Latest version of Chrome on Linux
  - Latest version of Firefox on Linux
- [ ] Not required

#### Data protection

- [x] Not relevant
- [ ] This adds new sources of PII and documents it and modifies Birdbath processors accordingly

#### Accessibility

- [ ] Automated WCAG 2.1 tests pass
- [ ] HTML validation passes
- [ ] Manual WCAG 2.1 tests completed
- [ ] I have tested in a screen reader
- [ ] I have tested in high-contrast mode
- [ ] Any animations removed for prefers-reduced-motion
- [x] Not required

#### Sustainability

- [ ] Images are optimised and lazy-loading used where appropriate
- [ ] SVGs have been optimised
- [ ] Perfomance and transfer of data considered
- [ ] If JavaScript is needed alternatives have been considered
- [x] Not required

#### Pattern library

- [ ] The pattern library component for this template displays correctly, and does not break parent templates
- [ ] The styleguide is updated if relevant
- [x] Changes are not relevant the pattern library

### CODE REVIEW

**Review by nimasmi — APPROVED** [review]
These changes look good, to me.

**Comment by helenb** [comment]
I will update the versions in the  'client sites and apps' Monday board in anticipation of this being merged

**Comment by helenb** [comment]
Note that https://github.com/torchbox/torchbox.com/pull/190 is shortly going to be merged to `main` and when this is done you'll need to update line 19 of `tbx/events/models.py` to remove `use_json_field=True`

**Comment by engineervix** [comment]
> Note that #190 is shortly going to be merged to `main` and when this is done you'll need to update line 19 of `tbx/events/models.py` to remove `use_json_field=True`

Done in [0d6adf5](https://github.com/torchbox/torchbox.com/pull/187/commits/0d6adf5e1bceab6a44c659da1d3ade1fc34a0363)

**Pull request merged**
