### PR TITLE
Fix the link for events in the listing, and sort markup

### PR DESCRIPTION
**Pull request by helenb**
[Link to Ticket update](https://torchbox.monday.com/boards/1192293412/pulses/1400769730/posts/220098515)

### Description of Changes Made

- Fix the links on the events listing page
- Change the markup so we don't output more than one `ul` per event - and ensure that the 'no results' text is in an `li` not a div, as it lands inside the `ul`

### How to Test

Create an events listing page on your local build, and add some test events. Try internal links, mailto links and external links. Ensure that they work

### Screenshots

<details>
  <summary>Expand to see more</summary>

</details>

### MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [ ] Tests and linting passes.

#### Unit tests

- [ ] Added
- [x] Not required

#### Documentation

- [ ] Updated build docs
- [ ] Updated editor guidelines (https://docs.google.com/document/d/1PAWccdQ4tfaZsrEWmpDhvP3GH5RRmBOARFVp4b-kje8/edit?usp=sharing)
- [x] Not required

#### Browser testing

- [x] I have tested in the following browsers and environments (edit the list as required)
  - Latest version of Chrome on mac
- [ ] Not required

#### Data protection

- [x] Not relevant
- [ ] This adds new sources of PII and documents it and modifies Birdbath processors accordingly

#### Accessibility

- [x] Automated WCAG 2.1 tests pass
- [ ] HTML validation passes
- [ ] Manual WCAG 2.1 tests completed
- [ ] I have tested in a screen reader
- [ ] I have tested in high-contrast mode
- [ ] Any animations removed for prefers-reduced-motion
- [ ] Not required

#### Sustainability

- [ ] Images are optimised and lazy-loading used where appropriate
- [ ] SVGs have been optimised
- [ ] Perfomance and transfer of data considered
- [ ] If JavaScript is needed alternatives have been considered
- [x] Not required

#### Pattern library

- [x] The pattern library component for this template displays correctly, and does not break parent templates
- [ ] The styleguide is updated if relevant
- [ ] Changes are not relevant the pattern library

### CODE REVIEW

**Review by engineervix — APPROVED** [review]
Thanks Helen, changes look good :+1:

**Comment by engineervix** [comment]
I will add a commit to update the copy to use in a situation where there are no events

**Comment by helenb** [comment]
@engineervix shall I get this merged as we're still waiting for the 'no events' content to be resolved?

**Comment by engineervix** [comment]
> @engineervix shall I get this merged as we're still waiting for the 'no events' content to be resolved?

yeah, maybe it can be merged then the copy issue can be addressed as a separate PR.

**Pull request merged**
