### PR TITLE
Development Database Snapshot Improvements

### PR DESCRIPTION
**Pull request by engineervix**
[Link to Ticket](https://torchbox.monday.com/boards/1192293412/pulses/1313170797)

### Description of Changes Made

- In addition to creating and restoring database snapshots, this adds additional database snapshot commands to list available snapshots and remove specified snapshots (220fc87).
- [Fabric](https://www.fabfile.org/) is updated to the latest version (a8ae8bf)
- Stellar is removed from the project, as it's not being used, and has issues (a8ae8bf)
- The README is updated to include information on database snapshots during development (54abf93)

### How to Test

- Checkout the `tooling/db-snapshot` branch and rebuild the Docker images with `fab build`
- start the Docker containers via `fab start`
- Test that you can create, list, restore and remove database snapshots. Here's an example:

```console
❯ fab dellar-snapshot my-sweet-backup
Database snapshot created
❯ fab dellar-snapshot another-aptly-named-backup
Database snapshot created
❯ fab dellar-list
Database snapshots:
 - another-aptly-named-backup
 - my-sweet-backup
Restore with `dellar-restore <snapshot>`
❯ fab dellar-remove my-sweet-backup
Snapshot my-sweet-backup removed
❯ fab dellar-restore another-aptly-named-backup
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
Database restored.
```

### MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [x] Tests and linting passes.

#### Unit tests

- [ ] Added
- [x] Not required

#### Documentation

- [x] Updated build docs
- [ ] Updated editor guidelines (https://docs.google.com/document/d/1PAWccdQ4tfaZsrEWmpDhvP3GH5RRmBOARFVp4b-kje8/edit?usp=sharing)
- [ ] Not required

#### Browser testing

- [ ] I have tested in the following browsers and environments (edit the list as required)
  - Latest version of Chrome on mac
  - Latest version of Firefox on mac
  - Latest version of Safari on mac
  - Safari on last two versions of iOS
  - Chrome on last two versions of Android
- [x] Not required

#### Data protection

- [x] Not relevant
- [ ] This adds new sources of PII and documents it and modifies Birdbath processors accordingly

#### Accessibility

- [ ] Automated WCAG 2.1 tests pass
- [ ] Manual WCAG 2.1 tests completed
- [ ] I have tested in a screen reader
- [ ] I have tested in high-contrast mode
- [ ] Any animations removed for prefers-reduced-motion
- [x] Not required

#### Sustainability

- [ ] Images are optimised and lazy-loading used where appropriate
- [ ] SVGs have been optimised
- [ ] Perfomance and transfer of data considered
- [ ] If JavaScript is needed alternatives have been considered
- [ ] New font variants have not been added
- [x] Not required

### CODE REVIEW

**Comment by helenb** [comment]
I haven't reviewed this yet but have quickly updated it to point at the integration branch rather than at `main`

**Comment by helenb** [comment]
Also tagging @ababic on this one as I don't feel most qualified to review the code. I will definitely test the changes though.

**Comment by helenb** [comment]
Tested and this is working well, thank you.

I can't see any files generated from this - there are two files in the database_dumps folder, but these appear to come from the staging data import, not from the dellar commands, based on the timing. I also can't see the files if I ssh into the db container in docker. I think this was why I thought it might not be working before - where would the files live? Can we document that? (and that you can expect database dump files to appear when you run a staging data import?)

**Comment by engineervix** [comment]
I've updated the docs with additional notes regarding location of backups.

**Comment by helenb** [comment]
I reviewed this with Andy and he's happy, and I can confirm I now see the files in the db container.

**Review by helenb — APPROVED** [review]

**Pull request merged**
