### PR TITLE
Remove wagtail-webstories

### PR DESCRIPTION
**Pull request by lparsons396**
[Link to Ticket](https://torchbox.monday.com/boards/1192293412/pulses/1389902143)

### Description of Changes Made
- Removes wagtail-webstories package and its dependencies
- This enables us to remove the ExternalStoryBlock which we no longer need (as per https://github.com/torchbox/torchbox.com/pull/22), along with amending the initial migrations involving it

### Screenshots

<details>
  <summary>Expand to see more</summary>

</details>

### MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [x] Tests and linting passes.

#### Unit tests

- [ ] Added
- [x] Not required

#### Documentation

- [ ] Updated build docs
- [ ] Updated editor guidelines (https://docs.google.com/document/d/1PAWccdQ4tfaZsrEWmpDhvP3GH5RRmBOARFVp4b-kje8/edit?usp=sharing)
- [x] Not required

#### Browser testing

- [ ] I have tested in the following browsers and environments (edit the list as required)
  - Latest version of Chrome on mac
  - Latest version of Firefox on mac
  - Latest version of Safari on mac
  - Safari on last two versions of iOS
  - Chrome on last two versions of Android
- [ ] Not required

#### Data protection

- [ ] Not relevant
- [ ] This adds new sources of PII and documents it and modifies Birdbath processors accordingly

#### Accessibility

- [ ] Automated WCAG 2.1 tests pass
- [ ] Manual WCAG 2.1 tests completed
- [ ] I have tested in a screen reader
- [ ] I have tested in high-contrast mode
- [ ] Any animations removed for prefers-reduced-motion
- [x] Not required

#### Sustainability

- [ ] Images are optimised and lazy-loading used where appropriate
- [ ] SVGs have been optimised
- [ ] Perfomance and transfer of data considered
- [ ] If JavaScript is needed alternatives have been considered
- [x] Not required

#### Pattern library

- [ ] The pattern library component for this template displays correctly, and does not break parent templates
- [ ] The styleguide is updated if relevant
- [x] Changes are not relevant the pattern library

### CODE REVIEW

**Review by engineervix — COMMENTED** [review]
Thanks @lparsons396 

This seems to be working well without any issues. However,  I'm not sure whether we should modify existing migration files, especially since they have already been applied to the production (and staging) database. My worry is that if we modify migration files after they have been applied, this may lead to inconsistencies between the models and the actual database schema. I don't know if there's a way we can test this to either confirm it or rule it out.

@nimasmi do you have any suggestions / comments on this?

**Comment by helenb** [comment]
> Thanks @lparsons396
> 
> This seems to be working well without any issues. However, I'm not sure whether we should modify existing migration files, especially since they have already been applied to the production (and staging) database. My worry is that if we modify migration files after they have been applied, this may lead to inconsistencies between the models and the actual database schema. I don't know if there's a way we can test this to either confirm it or rule it out.
> 
> @nimasmi do you have any suggestions / comments on this?

fwiw this approach was advised by @ababic when I discussed it with him a while ago - but interested in @nimasmi's thoughts too.

**Comment by nimasmi** [comment]
> Thanks @lparsons396
> 
> This seems to be working well without any issues. However, I'm not sure whether we should modify existing migration files, especially since they have already been applied to the production (and staging) database. My worry is that if we modify migration files after they have been applied, this may lead to inconsistencies between the models and the actual database schema. I don't know if there's a way we can test this to either confirm it or rule it out.
> 
> @nimasmi do you have any suggestions / comments on this?

In general, yes you're right: rewriting historical migrations that alter the schema does make Django think that those migrations have been run in their newly-edited form, and it may suggest a new migration to fix this.

e.g.

1. Add a field `foo` to MyModel
2. Generate migrations, e.g. `0003_mymodel_foo`
3. Generate migrations → no changes detected
4. Delete the `migrations.AddField()` step in `0003_mymodel_foo.py`
5. Generate migrations → Django will assume migration 0003 did nothing, and create another called `0004_mymodel_foo`

However, this PR makes changes to StreamField, and if you look at the migrations files, they result in `AlterField` migrations that record the expected JSON schema, but nothing that the database will enforce. They are not column or table level changes.

For this same reason we completely disregard StreamField content changes on some Wagtail projects, in order to prevent merge conflicts. It defies Django's default behaviour, but makes developers' lives easier.

**Comment by engineervix** [comment]
> > Thanks @lparsons396
> > This seems to be working well without any issues. However, I'm not sure whether we should modify existing migration files, especially since they have already been applied to the production (and staging) database. My worry is that if we modify migration files after they have been applied, this may lead to inconsistencies between the models and the actual database schema. I don't know if there's a way we can test this to either confirm it or rule it out.
> > @nimasmi do you have any suggestions / comments on this?
> 
> In general, yes you're right: rewriting historical migrations that alter the schema does make Django think that those migrations have been run in their newly-edited form, and it may suggest a new migration to fix this.
> 
> e.g.
> 
> 1. Add a field `foo` to MyModel
> 2. Generate migrations, e.g. `0003_mymodel_foo`
> 3. Generate migrations → no changes detected
> 4. Delete the `migrations.AddField()` step in `0003_mymodel_foo.py`
> 5. Generate migrations → Django will assume migration 0003 did nothing, and create another called `0004_mymodel_foo`
> 
> However, this PR makes changes to StreamField, and if you look at the migrations files, they result in `AlterField` migrations that record the expected JSON schema, but nothing that the database will enforce. They are not column or table level changes.
> 
> For this same reason we completely disregard StreamField content changes on some Wagtail projects, in order to prevent merge conflicts. It defies Django's default behaviour, but makes developers' lives easier.

Thanks for the explanation @nimasmi!

**Review by engineervix — APPROVED** [review]

**Pull request merged**
