### PR TITLE
Fix issue with results icon being clipped (featured case study)

### PR DESCRIPTION
**Pull request by helenb**
[Link to Ticket](https://torchbox.monday.com/boards/1192293412/pulses/1470140884)

### Description of Changes Made

Make the results icon on the featured case-study overflow:visible so the text doesn't get clipped

### Screenshots

<details>
  <summary>Expand to see more</summary>

Before:

Screenshot 2024-07-01 at 14 47 17

After:

Screenshot 2024-07-01 at 14 46 51

</details>

### MR Checklist

- [x] Add a description of your pull request and instructions for the reviewer to verify your work.
- [x] If your pull request is for a specific ticket, link to it in the description.
- [x] Stay on point and keep it small so the merge request can be easily reviewed.
- [x] Tests and linting passes.

#### Unit tests

- [ ] Added
- [x] Not required

#### Documentation

- [ ] Updated build docs
- [ ] Updated editor guidelines (See https://intranet.torchbox.com/torchbox-com-project-docs for the private link, for Torchbox employees only)
- [ ] Updated field spec (See https://intranet.torchbox.com/torchbox-com-project-docs for the private link, for Torchbox employees only)
- [x] Not required

#### Browser testing

- [x] I have tested in the following browsers and environments (edit the list as required)
  - Latest version of Chrome on mac
- [ ] Not required

#### Data protection

- [x] Not relevant
- [ ] This adds new sources of PII and documents it and modifies Birdbath processors accordingly

#### Accessibility

- [ ] Automated WCAG 2.1 tests pass
- [ ] HTML validation passes
- [ ] Manual WCAG 2.1 tests completed
- [ ] I have tested in a screen reader
- [ ] I have tested in high-contrast mode
- [ ] Any animations removed for prefers-reduced-motion
- [x] Not required

#### Sustainability

- [ ] Images are optimised and lazy-loading used where appropriate
- [ ] SVGs have been optimised
- [ ] Perfomance and transfer of data considered
- [ ] If JavaScript is needed alternatives have been considered
- [x] Not required

#### Pattern library

- [ ] The pattern library component for this template displays correctly, and does not break parent templates
- [ ] The styleguide is updated if relevant
- [x] Changes are not relevant the pattern library

### CODE REVIEW

**Comment by helenb** [comment]
Marking as draft for now as this accidentally includes all the light mode stuff.

**Comment by helenb** [comment]
> Marking as draft for now as this accidentally includes all the light mode stuff.

Now sorted out.

**Comment by chris-lawton** [comment]
I wonder if the viewbox attr is incorrect as it's odd that the SVG sits in the top left corner and there's a lot of space underneath and to the right of it.

<details><summary>Details</summary>
<p>

Screenshot 2024-07-03 at 09 27 16


</p>
</details> 

 Either that or there's a load of whitespace in the initial SVG. 

Anyways this MR fixes it : )

**Review by chris-lawton — APPROVED** [review]

**Comment by helenb** [comment]
> I wonder if the viewbox attr is incorrect as it's odd that the SVG sits in the top left corner and there's a lot of space underneath and to the right of it.
> 
> Details
> Either that or there's a load of whitespace in the initial SVG.
> 
> Anyways this MR fixes it : )

Yes I think the original SVG was a bit off - but going for the quick fix now :)

**Pull request merged**
